provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  filter-tweets:
    lang: go
    handler: ./filter-tweets
    image: ghcr.io/alexellis/filter-tweets:2021-12-08
    labels:
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
    secrets:
      - twitter-discord-webhook-url

